DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS budget CASCADE;
DROP TABLE IF EXISTS investment CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255)NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_digest VARCHAR(255) NOT NULL
);

CREATE TABLE budget (
id SERIAL PRIMARY KEY,
income INTEGER,
expenses INTEGER,
savings INTEGER,
user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE
);

CREATE TABLE investment (
id SERIAL PRIMARY KEY,
profile VARCHAR(255),
user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE
);
